name: needle

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      path:
        required: true
        type: string
      os:
        required: true
        type: string
      flags:
        required: true
        type: string

jobs:
  getneedle:
    runs-on: ${{ inputs.os }}
    steps:
    - name: Get Needle
      run: |
        git clone https://github.com/embroidermodder/needle needle-src
        mv needle-src/needle .
        chmod +x needle
    - name: Sew
      run: |
        ./needle ${{ inputs.flags }}
    - name: Upload Result
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.name }}
        path: ${{ inputs.path }}

