name: needle

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      os:
        required: true
        type: string
      flags:
        required: true
        type: string
    secrets:
      personal_access_token:
        required: true

jobs:
  getneedle:
    runs-on: ${{ inputs.os }}
    steps:
    - name: Get Needle
      run: |
        wget https://raw.githubusercontent.com/Embroidermodder/website/refs/heads/main/needle -O needle
        chmod +x needle
    - name: Sew
      run: |
        ./needle ${{ inputs.flags }}
    - name: Upload Result
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.name }}
        path: ./result.dat

